[package]
name = "countdown_speed_test"
version = "0.1.0"
authors = ["cainy-a <cainatkinson98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.8"